import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ModeToggle } from "@/components/theme-toggle";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          storageKey="app-theme"
          enableSystem={true}
        >
          {children}
          <Toaster richColors />
        </ThemeProvider>
        <footer className="px-2 md:px-9 bottom-0 bg-primary flex items-center justify-between">
          <p>@ 2024</p>
          <ModeToggle />
        </footer>
      </body>
    </html>
  );
}
